spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lib
    username: ${DB_USERNAME:masterpiece}
    password: ${DB_PASSWORD:zntPEGASUS77K}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  version:
    current: v1
    path-prefix: /api/{version}
    supported:
      - v1
      - v2