spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lib}
    username: ${SPRING_DATASOURCE_USERNAME:masterpiece}
    password: ${SPRING_DATASOURCE_PASSWORD:zntPEGASUS77K}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      hikari:
        connection-timeout: 30000
        maximum-pool-size: 10
        max-lifetime: 1800000
        initialization-fail-timeout: 0

api:
  version:
    current: v1
    path-prefix: /api/{version}
    supported:
      - v1
      - v2